
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ximsakib
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        singleBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        multiBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        offlineBtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        scoreBtn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        bestBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(186, 79, 84));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Welcome To");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("TIC TAC TOE");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("©kernel");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("A    G A M E     D E V E L O P E D    B Y    K E R N E  L");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 163, 163));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        singleBtn.setBackground(new java.awt.Color(255, 163, 163));
        singleBtn.setForeground(new java.awt.Color(255, 255, 255));
        singleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                singleBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                singleBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                singleBtnMouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(211, 211, 211));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("             Single Player");

        javax.swing.GroupLayout singleBtnLayout = new javax.swing.GroupLayout(singleBtn);
        singleBtn.setLayout(singleBtnLayout);
        singleBtnLayout.setHorizontalGroup(
            singleBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleBtnLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        singleBtnLayout.setVerticalGroup(
            singleBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(singleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 500, 60));

        multiBtn.setBackground(new java.awt.Color(255, 163, 163));
        multiBtn.setForeground(new java.awt.Color(255, 255, 255));
        multiBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                multiBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                multiBtnMouseExited(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(211, 211, 211));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("             Multi Player");

        javax.swing.GroupLayout multiBtnLayout = new javax.swing.GroupLayout(multiBtn);
        multiBtn.setLayout(multiBtnLayout);
        multiBtnLayout.setHorizontalGroup(
            multiBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiBtnLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        multiBtnLayout.setVerticalGroup(
            multiBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(multiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, 60));

        offlineBtn.setBackground(new java.awt.Color(255, 163, 163));
        offlineBtn.setForeground(new java.awt.Color(255, 255, 255));
        offlineBtn.setPreferredSize(new java.awt.Dimension(887, 642));
        offlineBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                offlineBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                offlineBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                offlineBtnMouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(211, 211, 211));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("            Offline Player");

        javax.swing.GroupLayout offlineBtnLayout = new javax.swing.GroupLayout(offlineBtn);
        offlineBtn.setLayout(offlineBtnLayout);
        offlineBtnLayout.setHorizontalGroup(
            offlineBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(offlineBtnLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        offlineBtnLayout.setVerticalGroup(
            offlineBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(offlineBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(offlineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 500, 60));

        scoreBtn.setBackground(new java.awt.Color(255, 163, 163));
        scoreBtn.setForeground(new java.awt.Color(255, 255, 255));
        scoreBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scoreBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                scoreBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                scoreBtnMouseExited(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(211, 211, 211));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("              Score Board");

        javax.swing.GroupLayout scoreBtnLayout = new javax.swing.GroupLayout(scoreBtn);
        scoreBtn.setLayout(scoreBtnLayout);
        scoreBtnLayout.setHorizontalGroup(
            scoreBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoreBtnLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        scoreBtnLayout.setVerticalGroup(
            scoreBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoreBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(scoreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

        bestBtn.setBackground(new java.awt.Color(255, 163, 163));
        bestBtn.setForeground(new java.awt.Color(255, 255, 255));
        bestBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bestBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bestBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bestBtnMouseExited(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(211, 211, 211));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("               Best Scores");

        javax.swing.GroupLayout bestBtnLayout = new javax.swing.GroupLayout(bestBtn);
        bestBtn.setLayout(bestBtnLayout);
        bestBtnLayout.setHorizontalGroup(
            bestBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bestBtnLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        bestBtnLayout.setVerticalGroup(
            bestBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bestBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(bestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, -1));

        exitBtn.setBackground(new java.awt.Color(255, 163, 163));
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(211, 211, 211));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("                    Exitt");

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, -1));

        jPasswordField1.setBackground(java.awt.Color.pink);
        jPasswordField1.setForeground(java.awt.Color.pink);
        jPasswordField1.setBorder(null);
        jPanel6.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, -100, 16, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(186, 79, 84));
        jLabel8.setText("Choose A Option");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jButton1.setBackground(new java.awt.Color(186, 79, 84));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign Out");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 75, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
                               

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {                                   
        //todo
    }
    
    private void singleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singleBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_singleBtnMouseClicked

    private void singleBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singleBtnMouseEntered
        setColor(singleBtn);
    }//GEN-LAST:event_singleBtnMouseEntered

    private void singleBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singleBtnMouseExited
        resetColor(singleBtn);
    }//GEN-LAST:event_singleBtnMouseExited

    private void multiBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiBtnMouseClicked
        
    }//GEN-LAST:event_multiBtnMouseClicked

    private void multiBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiBtnMouseEntered
        setColor(multiBtn);
    }//GEN-LAST:event_multiBtnMouseEntered

    private void multiBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiBtnMouseExited
        resetColor(multiBtn);
    }//GEN-LAST:event_multiBtnMouseExited

    private void offlineBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_offlineBtnMouseClicked
        PlayerNames player = new PlayerNames();
        player.show();
        dispose();
    }//GEN-LAST:event_offlineBtnMouseClicked

    private void offlineBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_offlineBtnMouseEntered
        setColor(offlineBtn);
    }//GEN-LAST:event_offlineBtnMouseEntered

    private void offlineBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_offlineBtnMouseExited
        resetColor(offlineBtn);
    }//GEN-LAST:event_offlineBtnMouseExited

    private void scoreBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoreBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreBtnMouseClicked

    private void scoreBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoreBtnMouseEntered
        setColor(scoreBtn);
    }//GEN-LAST:event_scoreBtnMouseEntered

    private void scoreBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoreBtnMouseExited
        resetColor(scoreBtn);
    }//GEN-LAST:event_scoreBtnMouseExited

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Confirm want to Exit ?","Tic Tac Toe",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        
        {
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        setColor(exitBtn);
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        resetColor(exitBtn);
    }//GEN-LAST:event_exitBtnMouseExited

    private void bestBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bestBtnMouseExited
        resetColor(bestBtn);
    }//GEN-LAST:event_bestBtnMouseExited

    private void bestBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bestBtnMouseEntered
        setColor(bestBtn);
    }//GEN-LAST:event_bestBtnMouseEntered

    private void bestBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bestBtnMouseClicked

    }//GEN-LAST:event_bestBtnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Welcome welcome = new Welcome();
        welcome.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    void setColor (JPanel panel) {
        panel.setBackground(new Color (186,79,84));
    }
    
    
    void resetColor (JPanel panel) {
        panel.setBackground(new Color (255,163,163));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bestBtn;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPanel multiBtn;
    private javax.swing.JPanel offlineBtn;
    private javax.swing.JPanel scoreBtn;
    private javax.swing.JPanel singleBtn;
    // End of variables declaration//GEN-END:variables
}
